- hosts: all
  become: true
  tasks: 
    -  name: delete old deployment
       command: kubectl delete -f /opt/deployment.yml
     - name: delete old service
       command: kubectl delete -f /opt/service.yml
     - name: create new deployment
       command: kubectl apply -f /opt/deployment.yml
     - name: create new service
       command: kubectl apply -f /opt/service.yml
